/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as TicTacToeRouteImport } from './routes/tic-tac-toe'
import { Route as RoyaltyRouteImport } from './routes/royalty'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoyaltyIndexRouteImport } from './routes/royalty.index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as RoyaltyWatchRouteImport } from './routes/royalty.watch'
import { Route as ChatRSlugRouteImport } from './routes/chat.r.$slug'

const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const TicTacToeRoute = TicTacToeRouteImport.update({
  id: '/tic-tac-toe',
  path: '/tic-tac-toe',
  getParentRoute: () => rootRouteImport,
} as any)
const RoyaltyRoute = RoyaltyRouteImport.update({
  id: '/royalty',
  path: '/royalty',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoyaltyIndexRoute = RoyaltyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoyaltyRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const RoyaltyWatchRoute = RoyaltyWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => RoyaltyRoute,
} as any)
const ChatRSlugRoute = ChatRSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai': typeof AiRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/royalty': typeof RoyaltyRouteWithChildren
  '/tic-tac-toe': typeof TicTacToeRoute
  '/timer': typeof TimerRoute
  '/royalty/watch': typeof RoyaltyWatchRoute
  '/chat/': typeof ChatIndexRoute
  '/royalty/': typeof RoyaltyIndexRoute
  '/chat/r/$slug': typeof ChatRSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/tic-tac-toe': typeof TicTacToeRoute
  '/timer': typeof TimerRoute
  '/royalty/watch': typeof RoyaltyWatchRoute
  '/chat': typeof ChatIndexRoute
  '/royalty': typeof RoyaltyIndexRoute
  '/chat/r/$slug': typeof ChatRSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai': typeof AiRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/royalty': typeof RoyaltyRouteWithChildren
  '/tic-tac-toe': typeof TicTacToeRoute
  '/timer': typeof TimerRoute
  '/royalty/watch': typeof RoyaltyWatchRoute
  '/chat/': typeof ChatIndexRoute
  '/royalty/': typeof RoyaltyIndexRoute
  '/chat/r/$slug': typeof ChatRSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/ai'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/royalty'
    | '/tic-tac-toe'
    | '/timer'
    | '/royalty/watch'
    | '/chat/'
    | '/royalty/'
    | '/chat/r/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/ai'
    | '/dashboard'
    | '/login'
    | '/tic-tac-toe'
    | '/timer'
    | '/royalty/watch'
    | '/chat'
    | '/royalty'
    | '/chat/r/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/ai'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/royalty'
    | '/tic-tac-toe'
    | '/timer'
    | '/royalty/watch'
    | '/chat/'
    | '/royalty/'
    | '/chat/r/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AiRoute: typeof AiRoute
  ChatRoute: typeof ChatRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RoyaltyRoute: typeof RoyaltyRouteWithChildren
  TicTacToeRoute: typeof TicTacToeRoute
  TimerRoute: typeof TimerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tic-tac-toe': {
      id: '/tic-tac-toe'
      path: '/tic-tac-toe'
      fullPath: '/tic-tac-toe'
      preLoaderRoute: typeof TicTacToeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/royalty': {
      id: '/royalty'
      path: '/royalty'
      fullPath: '/royalty'
      preLoaderRoute: typeof RoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/royalty/': {
      id: '/royalty/'
      path: '/'
      fullPath: '/royalty/'
      preLoaderRoute: typeof RoyaltyIndexRouteImport
      parentRoute: typeof RoyaltyRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/royalty/watch': {
      id: '/royalty/watch'
      path: '/watch'
      fullPath: '/royalty/watch'
      preLoaderRoute: typeof RoyaltyWatchRouteImport
      parentRoute: typeof RoyaltyRoute
    }
    '/chat/r/$slug': {
      id: '/chat/r/$slug'
      path: '/r/$slug'
      fullPath: '/chat/r/$slug'
      preLoaderRoute: typeof ChatRSlugRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatRSlugRoute: typeof ChatRSlugRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatRSlugRoute: ChatRSlugRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface RoyaltyRouteChildren {
  RoyaltyWatchRoute: typeof RoyaltyWatchRoute
  RoyaltyIndexRoute: typeof RoyaltyIndexRoute
}

const RoyaltyRouteChildren: RoyaltyRouteChildren = {
  RoyaltyWatchRoute: RoyaltyWatchRoute,
  RoyaltyIndexRoute: RoyaltyIndexRoute,
}

const RoyaltyRouteWithChildren =
  RoyaltyRoute._addFileChildren(RoyaltyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AiRoute: AiRoute,
  ChatRoute: ChatRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RoyaltyRoute: RoyaltyRouteWithChildren,
  TicTacToeRoute: TicTacToeRoute,
  TimerRoute: TimerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
